name: example-environment
channels:
  - conda-forge
dependencies:
  - cartopy
  - python 3.7.3
  - matplotlib
  - numpy
  - folium
  - xarray
  - requests
  - pandas
  - json2html
  - xmltodict
  - netCDF4