name: example-environment
channels:
  - conda-forge
dependencies:
  - cartopy
  - pip
    - json2html
    - xmltodict
    - netCDF4
    - xarray
    - matplotlib
    - numpy
    - folium
    - requests
    - pandas