name: example-environment
channels:
  - conda-forge
dependencies:
  - cartopy
  - pip:
    - requests==2.21.0
    - pandas==0.24.2
    - json2html==1.3.0
    - matplotlib==3.0.3
    - folium==0.8.3
    - OWSLib==0.17.1
    - xmltodict==0.12.0
    - netCDF4==1.4.2
    - xarray==0.12.1